# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e92e94670f3bfed01ab33474e580428ad142f44d7479438480ced1f21d655687de606d77c51f19f20fec940e77816696f0bb68b93a3ef969627dc040ecefc661

test:
  secret_key_base: 5ae00cac550606896cd034b04b131ddedd233d9e62b85179ae6e8edaaabb859a0b41ce0d829052e4b6d2feea6a644e1370970361f45372378945bf91fb6c93c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
